---
# health checks tasks 
- name: Set output file name - pre-upgrade
  ansible.builtin.set_fact:
    output_file: "{{ tmp_base_dir }}/{{ git_repo_subdir_path }}/{{ pre_upgrade_health_checks_file }}" 
  when: pre_upgrade

- name: Set output file name - post-upgrade
  ansible.builtin.set_fact:
    output_file: "{{ tmp_base_dir }}/{{ git_repo_subdir_path }}/{{ post_upgrade_health_checks_file }}"
  when: post_upgrade

- name: Generate list of commands to run for healthchecks
  ansible.builtin.set_fact:
    command_list: "{{ lookup('file', '{{ health_check_commands_file }}').splitlines() }}"
  delegate_to: localhost

- name: Perform health checks on device
  ansible.builtin.include_role:
    name: role-juniper-health
  vars:
    _health_: true
    _tmp_root_dir_: "{{ tmp_base_dir }}"
    _commands_list_: "{{ command_list }}" # Should be a list of commands
    _output_file_: "{{ output_file }}"
