---
# Git diff tasks

# - name: Do a diff if on post_check stage
#   ansible.builtin.shell: |
#     /bin/vimdiff "{{ inventory_hostname_dir_path }}/{{ pre_checks_output_file }}" "{{ inventory_hostname_dir_path }}/{{ post_checks_output_file }}" -c 'let g:html_number_lines = 1' -c TOhtml -c "w! {{ inventory_hostname_dir_path }}/{{ diff_file }} | qa!"
#   delegate_to: localhost
#   # when: post_checks

- name: Create diff in html format during post
  ansible.builtin.include_role:
    name: tpg.ndecollection.diffutils
  vars:
    file_pre: "{{ inventory_hostname_dir_path }}/{{ pre_checks_output_file }}"
    file_post: "{{ inventory_hostname_dir_path }}/{{ post_checks_output_file }}"
    file_output_html: "{{ inventory_hostname_dir_path }}/{{ diff_file }}"
    colour_scheme: "dark"