---
- name: "Run command => {{ command }}"
  junipernetworks.junos.junos_command:
    commands: "{{ command }}"
    # display: set
  register: command_output
  ignore_errors: true

# regex_replace('\r\n', '\n'): Ensures that the configuration is formatted properly with new lines,
# in case the original output contains carriage return and line feed (\r\n).
- name: Ensure the command output is properly formatted
  ansible.builtin.set_fact:
    formatted_config: "{{ command_output.stdout[0] | regex_replace('\r\n', '\n') }}"
  delegate_to: localhost
  ignore_errors: true
  when: command_output["failed"] == false

- name: Append the checks to a file
  ansible.builtin.shell: |
    echo '' >> {{ tmp_cmd_output_store }}
    echo '==>{{ command }}' >> {{ tmp_cmd_output_store }}
    echo '{{ formatted_config }}' >> {{ tmp_cmd_output_store }}
  delegate_to: localhost
  ignore_errors: true
  when: command_output["failed"] == false
