---
- name: Set file name - If pre upgrade
  ansible.builtin.set_fact:
    file_name: "pre-upgrade-health-checks-{{ command | replace(' ', '_') }}.txt"
  delegate_to: locahost
  ignore_errors: true
  when: pre_check

- name: Set file name - If post upgrade
  ansible.builtin.set_fact:
    file_name: "post-upgrade-health-checks-{{ command | replace(' ', '_') }}.txt"
  delegate_to: locahost
  ignore_errors: true
  when: post_check

- name: "Run command => {{ command }}"
  junipernetworks.junos.junos_command:
    commands: "{{ command }}"
    # display: set
  register: command_output
  ignore_errors: true

- name: Save output to a dynamically named file
  ansible.builtin.copy:
    content: "{{ command_output.stdout[0] | regex_replace('\r\n', '\n') }}"
    dest: "{{ tmp_root_dir }}/{{ file_name }}"
  delegate_to: locahost
  ignore_errors: true