---
# Collect junos facts

- name: Gather Junos-specific facts - PRE-UPGRADE
  junipernetworks.junos.junos_facts:
    gather_subset:
      - hardware        # Hardware-related facts like chassis info
      - config         # Configuration information
      #- interfaces     # Interface details
      - default         # default values
  register: junos_facts
  ignore_errors: true
    
- name: Debug device details
  ansible.builtin.debug:
    msg: 
      - "software version : {{ junos_facts.ansible_facts.ansible_net_version }}"
      - "device model     : {{ junos_facts.ansible_facts.ansible_net_model  }}"
      - "total memory(mb) : {{ junos_facts.ansible_facts.ansible_net_memtotal_mb }}"
      - "free memory(mb)  : {{ junos_facts.ansible_facts.ansible_net_memfree_mb }}"


- name: "Write junos ansible facts to {{ tmp_root_dir }}/{{ file_name }}"
  ansible.builtin.shell: |
    echo "" >> {{ tmp_root_dir }}/{{ file_name }}
    echo "##### JUNOS ANSIBLE FACTS ####" >> {{ tmp_root_dir }}/{{ file_name }}
    echo "software version = {{ junos_facts.ansible_facts.ansible_net_version }}" >> {{ tmp_root_dir }}/{{ file_name }}
    echo "device model     = {{ junos_facts.ansible_facts.ansible_net_model  }}" >> {{ tmp_root_dir }}/{{ file_name }}
    echo "RE0 Status       : {{ junos_facts.ansible_facts.ansible_net_routing_engines['0']['status']  }}" >> {{ tmp_root_dir }}/{{ file_name }}
    echo "RE0 Master state = {{ junos_facts.ansible_facts.ansible_net_routing_engines['0']['mastership_state'] }}" >> {{ tmp_root_dir }}/{{ file_name }}
    echo "RE0 temperature  : {{ junos_facts.ansible_facts.ansible_net_routing_engines['0']['temperature']  }}" >> {{ tmp_root_dir }}/{{ file_name }}
    echo "RE0 uptime       : {{ junos_facts.ansible_facts.ansible_net_routing_engines['0']['up_time']  }}" >> {{ tmp_root_dir }}/{{ file_name }}
    echo "RE1 Status       : {{ junos_facts.ansible_facts.ansible_net_routing_engines['1']['status']  }}" >> {{ tmp_root_dir }}/{{ file_name }}
    echo "RE1 Master state : {{ junos_facts.ansible_facts.ansible_net_routing_engines['1']['mastership_state']  }}" >> {{ tmp_root_dir }}/{{ file_name }}
    echo "RE1 temperature  : {{ junos_facts.ansible_facts.ansible_net_routing_engines['1']['temperature']  }}" >> {{ tmp_root_dir }}/{{ file_name }}
    echo "RE1 uptime       : {{ junos_facts.ansible_facts.ansible_net_routing_engines['1']['up_time'] }}" >> {{ tmp_root_dir }}/{{ file_name }}
  delegate_to: localhost
  ignore_errors: true
  